document_templates = {
    "feasibility study": {
        "Introduction": "Provide an overview of the project and its objectives.",
        "Executive Summary": "Summarize the key findings and recommendations of the feasibility study.",
        "Market Analysis": "Assess the target market, competition, and potential demand for the project.",
        "Technical Feasibility": "Evaluate the technical requirements and constraints of the project.",
        "Financial Analysis": "Perform a financial analysis, including cost estimation, revenue projections, and return on investment.",
        "Risk Assessment": "Identify and evaluate potential risks and mitigation strategies.",
        "Conclusion": "Summarize the overall feasibility of the project and provide recommendations for further action.",
        "References": "Include a list of references cited in the feasibility study.",
    },
    "research paper": {
        "Abstract": "Provide a brief summary of the research paper.",
        "Introduction": "Introduce the topic and provide background information.",
        "Literature Review": "Review relevant literature and previous research on the topic.",
        "Methodology": "Describe the research methodology and data collection techniques used.",
        "Results": "Present the findings and results of the research.",
        "Discussion": "Discuss the implications of the results and their significance.",
        "Conclusion": "Summarize the main findings and provide recommendations for future research.",
        "References": "Include a list of references cited in the research paper.",
    },
    "business proposal": {
        "Executive Summary": "Provide a brief overview of the business proposal.",
        "Company Description": "Describe the company, its mission, and core values.",
        "Market Analysis": "Analyze the target market, competition, and customer needs.",
        "Product or Service Description": "Provide details about the product or service offered.",
        "Marketing and Sales Strategy": "Outline the marketing and sales strategies to promote the product or service.",
        "Financial Projections": "Present the financial projections, including revenue, costs, and profitability.",
        "Implementation Plan": "Describe the implementation plan and timeline for executing the business proposal.",
        "Conclusion": "Summarize the key points and benefits of the business proposal.",
    },
    "thesis": {
        "Abstract": "Provide a concise summary of the thesis.",
        "Introduction": "Introduce the research topic and objectives.",
        "Literature Review": "Review relevant literature and previous studies related to the research.",
        "Methodology": "Describe the research methodology and data collection techniques.",
        "Results": "Present the results and findings of the research.",
        "Discussion": "Analyze and discuss the results in relation to the research objectives.",
        "Conclusion": "Summarize the main findings and their implications.",
        "References": "Include a list of references cited in the thesis.",
    },
    "feasibility study": {
        "Introduction": "Provide an overview of the project and its objectives.",
        "Executive Summary": "Summarize the key findings and recommendations of the feasibility study.",
        "Market Analysis": "Assess the target market, competition, and potential demand for the project.",
        "Technical Feasibility": "Evaluate the technical requirements and constraints of the project.",
        "Financial Analysis": "Perform a financial analysis, including cost estimation, revenue projections, and return on investment.",
        "Risk Assessment": "Identify and evaluate potential risks and mitigation strategies.",
        "Conclusion": "Summarize the overall feasibility of the project and provide recommendations for further action.",
        "References": "Include a list of references cited in the feasibility study.",
    },
}
